apiVersion: apps/v1
kind: Deployment
metadata:
  name: facade-k8s-deployment
  labels:
    app: facade-k8s-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: facade-k8s-app
  template:
    metadata:
      labels:
        app: facade-k8s-app
    spec:
      containers:
      - name: facade-k8s 
        image: markoshlima/facade-k8s:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8080